spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/thesis_manage?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bfhdm210


server:
  port: 8090

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false